TypeError: int argument required, fixed
git-svn-id: file:///home/svn/omero/trunk@5346 05709c45-44f0-0310-885b-81a1db45b4a6

Former-commit-id: b436671482d55a0c746a75a8a3836b503d1a81c4