hql.py: when querying masks, filter `bytes` field
`omero hql "select s from Shape s"` or similar fails with

```
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb0' in position 3797: surrogates not allowed
```

due to the bytes field.